let gameseq=[];     //will store bot side
let userseq=[];         //will store user side

let started=false;
let level=0;

let btns=["yellow","red","purple","green"];                      //will use it to make random  btn flash(by bot side)

let h2=document.querySelector("h2");

document.addEventListener("keypress",function(){                        //starts game when any key gets pressed(any valued key)
    if(started==false){
        console.log("game started");
        started=true;
        levelup();
    }
})

function gameflash(btn){                                        //flash white when bot plays(btn get clicked automatically)
    btn.classList.add("gameflash");
    setTimeout(function(){
        btn.classList.remove("gameflash");                     //to make it flash-make btn white for 1 sec
    }, 200);
}

function userflash(btn){                                      //flash black when user click btn
    btn.classList.add("userflash");
    setTimeout(function(){
        btn.classList.remove("userflash"); 
    }, 200);
}

function levelup(){
    userseq=[];                                            //as level ups, user has to put sequence from start
    level++;
    h2.innerText=`Level ${level}`;
    
    let randomidx=Math.floor(Math.random()*3);              //generate random num 0-3(indices of btns arr)
    let randcolor=btns[randomidx];
    let randbtn=document.querySelector(`.${randcolor}`);     //give access to particular color(random color) class

    gameflash(randbtn);                                         //flash random btn

    gameseq.push(randcolor);                                //keep track of bot side- pushing random color generated by bot in arr
    // console.log(gameseq);
    
    //after pressing any key at start, random color will be ganerated and that color btn will be flashed and leveled up
}

//btn will flash if user clicks or automatically

function btnpress(){                                //user side
    let btn=this;                                      //this will indicate which btn was pressed

    userflash(btn);                                       //flash btn pressed by user

    usercolor=btn.getAttribute("id");
    userseq.push(usercolor);                               //keep track of user
    // console.log(userseq);

    checkans(userseq.length-1);                        //check every btn pressed by user with gameseq
}

let allbtns=document.querySelectorAll(".btn");
for(btn of allbtns){
    btn.addEventListener("click",btnpress);
}

function checkans(idx){                                              //to check ans by user
    // let idx= level-1;                                           //level= size of userseq and gameseq

    if(userseq[idx] == gameseq[idx]){
        // console.log("same value");                         //if value is same then two cases

        if(userseq.length==gameseq.length){                       //if user is correct till last, now it will be bot turn to play (levelup)
            setTimeout(levelup,1000);                                          
        }else{                         //user is in middle of his turn-he is still playing his turn                                           
            
        }
    }else{
        h2.innerHTML=`Game over!! Your Score:<b> ${level} </b>  <br>Press any key to start`;

        document.querySelector("body").style.backgroundColor="red";
        setTimeout(function(){
            document.querySelector("body").style.backgroundColor="white";
        }, 100);

        reset();
    }
}

function reset(){                                    //works when game is over
    started=false;
    gameseq=[];
    userseq=[];
    level=0;

}